CC = gcc

0000:
	$(CC) -o memset-0000-control.exe memset-0000-control.c

1111:
	$(CC) -o memset-1111.exe memset-1111.c

2111:
	$(CC) -o memset-2111.exe memset-2111.c

all:
	$(MAKE) 0000
	$(MAKE) 1111
	$(MAKE) 2111

clean: 
	rm -f *.o *.exe *.so
